FROM node:22-alpine3.19

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools
RUN ls -a
RUN npm install -g nodemon
RUN npm install -d
EXPOSE 4001

CMD [ "npm", "run", "dev" ]
